# Generated by Django 4.2.1 on 2023-05-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muralista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=9)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='muralista',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muralista.contacto'),
        ),
        migrations.AlterField(
            model_name='muralista',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muralista.estilo'),
        ),
    ]
