# Generated by Django 4.2.1 on 2023-05-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muralista', '0002_contacto_estilo_alter_muralista_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rgb', models.CharField(max_length=200)),
                ('red', models.CharField(max_length=200)),
                ('green', models.CharField(max_length=200)),
                ('blue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('idPaleta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muralista.color')),
                ('muralista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muralista.muralista')),
            ],
        ),
    ]
